<?php namespace TwitterFeed; ?>
<p>
	Here is a short tutorial to get you up and running quickly. 
	At the end of this tutorial you will be able the use the Askupa Twitter Feed plugin to show twitter account feeds as a static list, sliding list and scrolling list. 
	You will also learn how to add a Twitter feed widget to your sidebar.
</p>
<h2>Introduction</h2>
<p>
	You can use the plugin to add tweets in two ways: As shortcodes or as a widget. You can add a shortcode to your posts or pages by getting to the editing section and clicking on the blue bird icon. 
	from the dropdown list you can select
</p>
<h2>Static Tweet List</h2>
<ol class="askupa-list">
	<li><strong>Step One</strong> - Click on the Twitter Feed icon located on the rich editing panel
		<img src="<?php echo PLUGIN_URL; ?>assets/img/rich-editing-button.png" class="aligncenter"/>
	</li>
	<li><strong>Step Two</strong> - Choose "Tweet List" from the dropdown menu
		<img src="<?php echo PLUGIN_URL; ?>assets/img/button-menu.png" class="aligncenter"/>
	</li>
	<li><strong>Step Three</strong> - Use the shortcode editor to setup the tweet list. You can choose a skin, the number of tweets, and which tweet assets to show.
		<img src="<?php echo PLUGIN_URL; ?>assets/img/popup.png" class="aligncenter"/>
	</li>
</ol>
<h2>Scrolling Tweet List</h2>
<ol class="askupa-list">
	<li><strong>Step One</strong> - Click on the Twitter Feed icon located on the rich editing panel</li>
	<li><strong>Step Two</strong> - Choose "Scrolling Tweet List" from the dropdown menu</li>
	<li><strong>Step Three</strong> - Use the shortcode editor to setup the scrolling tweet list. You can choose a skin, the number of tweets, which tweet assets to show and the time between each scroll.</li>
</ol>
<h2>Sliding Tweet List</h2>
<ol class="askupa-list">
	<li><strong>Step One</strong> - Click on the Twitter Feed icon located on the rich editing panel</li>
	<li><strong>Step Two</strong> - Choose "Sliding Tweet List" from the dropdown menu</li>
	<li><strong>Step Three</strong> - Use the shortcode editor to setup the scrolling tweet list. You can choose a skin, the number of tweets, which tweet assets to show and the time between each scroll.</li>
</ol>
<h2>Twitter Feed Widget</h2>
<ol class="askupa-list">
	<li><strong>Step One</strong> - Click on Appearance -> Widgets
		<img src="<?php echo PLUGIN_URL; ?>assets/img/appearance.png" class="aligncenter"/>
	</li>
	<li><strong>Step Two</strong> - Drag "Twitter Feed Widget" to one of the sidebars to activate it.
		<img src="<?php echo PLUGIN_URL; ?>assets/img/widgets.png" class="aligncenter"/>
	</li>
	<li><strong>Step Three</strong> - Use the widget settings panel to choose the user name, skin and assets. This plugin supports multi-widget, so you can add as many Twitter Feed widgets as you want, each of which with its own settings.
		<img src="<?php echo PLUGIN_URL; ?>assets/img/twitter-feed-widget.jpg" class="aligncenter"/>
	</li>
</ol>
